# Generated by Django 3.0.3 on 2020-05-27 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_canal', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=64)),
                ('enlace', models.URLField()),
                ('votos', models.IntegerField()),
                ('num_elementos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('enlace', models.URLField()),
                ('descripcion', models.CharField(max_length=1024)),
                ('alimentador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis_cosas_app.Alimentador')),
            ],
        ),
    ]
