# Generated by Django 3.0.3 on 2020-06-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentador',
            name='num_elementos',
        ),
    ]
