# Generated by Django 3.0.3 on 2020-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0003_voto'),
    ]

    operations = [
        migrations.CreateModel(
            name='pepe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_canal', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=64)),
                ('enlace', models.URLField()),
                ('votos', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Voto',
        ),
    ]
