# Generated by Django 3.0.3 on 2020-06-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0004_auto_20200618_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pepe',
        ),
    ]
