# Generated by Django 3.0.3 on 2020-06-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0005_delete_pepe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='alimentador',
        ),
    ]
