# Generated by Django 3.0.3 on 2020-06-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0009_auto_20200618_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='video_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
