# Generated by Django 3.0.3 on 2020-06-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0012_auto_20200618_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='descripcion',
        ),
    ]
