# Generated by Django 3.0.3 on 2020-06-19 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0015_auto_20200618_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alimentador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mis_cosas_app.Alimentador'),
        ),
    ]
