# Generated by Django 3.0.3 on 2020-06-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0016_item_alimentador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimentador',
            name='votos',
        ),
    ]
