# Generated by Django 3.0.3 on 2020-07-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0018_fotodeperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='pepe',
            fields=[
                ('nombre', models.CharField(max_length=64)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('enlace', models.URLField()),
                ('descripcion', models.CharField(max_length=1024, null=True)),
                ('alimentador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mis_cosas_app.Alimentador')),
            ],
        ),
    ]
