# Generated by Django 3.0.3 on 2020-07-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0019_pepe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pepe',
        ),
    ]
