# Generated by Django 3.0.3 on 2020-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0020_delete_pepe'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentador',
            name='seleccionado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fotodeperfil',
            name='foto',
            field=models.ImageField(default='PERFIL-HUEVO.jpg', upload_to='media'),
        ),
    ]
