# Generated by Django 3.0.3 on 2020-07-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0023_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='puntuacion',
            field=models.IntegerField(null=True),
        ),
    ]
