# Generated by Django 3.0.3 on 2020-07-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0028_item_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentador',
            name='tipo',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
