# Generated by Django 3.0.3 on 2020-07-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0029_alimentador_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
