# Generated by Django 3.0.3 on 2020-07-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0031_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='voto_negativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='voto_positivo',
            field=models.BooleanField(default=False),
        ),
    ]
