# Generated by Django 3.0.3 on 2020-07-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0032_auto_20200717_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='voto_negativo',
        ),
        migrations.RemoveField(
            model_name='item',
            name='voto_positivo',
        ),
        migrations.AddField(
            model_name='item',
            name='votos_negativo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='votos_positivo',
            field=models.IntegerField(default=0),
        ),
    ]
