# Generated by Django 3.0.3 on 2020-07-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis_cosas_app', '0033_auto_20200717_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='votos_negativo',
            new_name='votos_negativos',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='votos_positivo',
            new_name='votos_positivos',
        ),
    ]
